version: "3.7"


services:

  postgres:
    hostname: beauty_link
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beauty_link
    ports:
      - "5434:5432"
    env_file:
      - src/config/.env

volumes:
  postgres_data:

